apiVersion: 1
datasources:
  - name: victoria-metrics
    type: prometheus
    url: https://metrics.blkjy.io
    access: server
    isDefault: true
    basicAuth: true
    basicAuthUser: blockjoy
    secureJsonData:
      basicAuthPassword: "${GRAFANA_PROM_BASICAUTH}"
  - name: grafanacloud-logs
    type: loki
    url: https://logs-prod-012.grafana.net
    access: server
    isDefault: false
    basicAuth: true
    basicAuthUser: 760471
    secureJsonData:
      basicAuthPassword: "${GRAFANA_LOKI_API_KEY}"
